spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lingo-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      connection-timeout: 3000
      initialization-fail-timeout: -1
  jpa:
    hibernate:
      ddl-auto: update # 상용때는 반드시 validate
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      repositories:
        enabled: false
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
  elasticsearch:
    uris: ${ELASTICSEARCH_URL}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}


jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET_KEY}
  token:
    expiration: ${JWT_TOKEN_EXP}
  refresh:
    expiration: ${JWT_REFRESH_EXP}

oauth:
  kakao:
    api: ${KAKAO_OAUTH_API}

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region:
    static: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}

self-auth:
  client_id: ${SELF_AUTH_CLIENT_ID}
  client_secret: ${SELF_AUTH_CLIENT_SECRET}
  return_url: ${SELF_AUTH_RETURN_URL}
  product_id: ${SELF_AUTH_PRODUCT_ID}
  url: ${SELF_AUTH_URL}

ringo:
  config:
    survey:
      space_weight: 0.2
      self_representation_weight: 0.3
      content_weight: 0.25
      sharing_weight: 0.25

springdoc:
  swagger-ui:
    operations-sorter: alpha
  #server-url: https://ringolinkgo.com

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - metrics
  endpoint:
    prometheus:
      enabled: true

discord:
  webhook:
    alert:
      url: ${DISCORD_WEBHOOK_URL}

logging:
  level:
    com.lingo.lingoproject: debug
    #org.springframework.messaging: DEBUG
    #org.springframework.web.socket: TRACE
    #org.springframework.web.socket.messaging: DEBUG
    #org.springframework.security: DEBUG

#logging:
#  level:
#    org.springframework.messaging: DEBUG
#    org.springframework.web.socket: TRACE
#    org.springframework.web.socket.messaging: DEBUG
